import cityOne from "../../assets/city/dhaka.webp";
import cityTwo from "../../assets/city/chittagong.webp";
import cityThree from "../../assets/city/sylhet.webp";
import cityFour from "../../assets/city/rajshahi.webp";
import cityFive from "../../assets/city/khulna.webp";
import citySix from "../../assets/city/Barisal.webp";
import citySeven from "../../assets/city/rangpur.webp";
import cityEight from "../../assets/city/mymensingh.webp";

const cities = [
  { name: "Dhaka", image: cityOne },
  { name: "Chattogram", image: cityTwo },
  { name: "Sylhet", image: cityThree },
  { name: "Khulna", image: cityFour },
  { name: "Rajshahi", image: cityFive },
  { name: "Barisal", image: citySix },
  { name: "Cox's Bazar", image: citySeven },
  { name: "Rangpur", image: cityEight },
  { name: "Mymensingh", image: cityOne },
  { name: "Comilla", image: cityTwo },
  { name: "Narayanganj", image: cityThree },
  { name: "Gazipur", image: cityFour },
  { name: "Jessore", image: cityFive },
  { name: "Bogra", image: citySix },
  { name: "Tangail", image: citySeven },
  { name: "Narsingdi", image: cityEight },
  { name: "Madaripur", image: cityOne },
  { name: "Pabna", image: cityTwo },
  { name: "Noakhali", image: cityThree },
  { name: "Kushtia", image: cityFour },
  { name: "Feni", image: cityFive },
  { name: "Dinajpur", image: citySix },
  { name: "Jhenaidah", image: citySeven },
  { name: "Satkhira", image: cityEight },
  { name: "Brahmanbaria", image: cityOne },
  { name: "Naogaon", image: cityTwo },
  { name: "Chuadanga", image: cityThree },
];

const food_categories = [
  "American",
  "Asian",
  "Bakery",
  "Bangladeshi",
  "Bengali",
  "Beverage",
  "Biriyani",
  "Breakfast",
  "Burgers",
  "Cafe",
  "Cakes",
  "Chicken",
  "Chinese",
  "Chotpoti & Fuchka",
  "Curry",
  "Dessert",
  "Dumpling",
  "Fast Food",
  "Fish",
  "Fried Chicken",
  "Healthy",
  "Ice Cream",
  "Indian",
  "Italian",
  "Japanese",
  "Juice Corner",
  "Kashmiri",
  "Kebab",
  "Korean",
  "Meat",
  "Mediterranean",
  "Middle Eastern",
  "Noodles",
  "Pasta",
  "Pizza",
  "Rice Dishes",
  "Sandwiches",
  "Seafood",
  "Shawarma",
  "Snacks",
  "Soups",
  "Steak",
  "Sushi",
  "Sweets",
  "Thai",
  "Turkish",
  "Vegetarian",
  "Western",
  "Wraps",
];

export { cities, food_categories };
